services:
  postgres:
    image: postgres:15
    container_name: postgres-db-gravita
    restart: always
    environment:
      POSTGRES_DB: gravita_db
      POSTGRES_USER: gravita
      POSTGRES_PASSWORD: gravita
      PGTZ: UTC
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres_data:
