services:
  #  app:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: gravita-app
  #    restart: on-failure
  #    depends_on:
  #      - postgres
  #      - localstack
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      SPRING_PROFILES_ACTIVE: local
  #      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gravita_db
  #      SPRING_DATASOURCE_USERNAME: gravita
  #      SPRING_DATASOURCE_PASSWORD: gravita
  #      AWS_SQS_ENDPOINT: http://localstack:4566
  #      AWS_SQS_EMAIL_QUEUE_URL: http://localstack:4566/000000000000/gravita-email-notifications

  postgres:
    image: postgres:15
    container_name: postgres-db-gravita
    restart: always
    environment:
      POSTGRES_DB: gravita_db
      POSTGRES_USER: gravita
      POSTGRES_PASSWORD: gravita
      PGTZ: UTC
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  localstack:
    image: localstack/localstack:latest
    container_name: localstack-gravita
    ports:
      - "4566:4566"
    environment:
      DEBUG: 0
      PERSISTENCE: 1
      LOCALSTACK_AUTH_TOKEN: "ls-FIXUWEze-YOGi-2493-yIde-Wape833851c9"
    volumes:
      - localstack_data:/var/lib/localstack
      - ./localstack/init/ready.d:/etc/localstack/init/ready.d:ro
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  postgres_data:
  localstack_data:
