spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration/local

aws.sqs.endpoint=http://localhost:4566
aws.sqs.email-queue-url=http://localhost:4566/000000000000/gravita-email-notifications
aws.access-key=test
aws.secret-key=test

