spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration/prod

aws.sqs.email-queue-url=${AWS_SQS_EMAIL_QUEUE_URL}
aws.sqs.whatsapp-queue-url=${AWS_SQS_WHATSAPP_QUEUE_URL}

notifications.purchasing.approver-email=${PURCHASING_APPROVER_EMAIL}
notifications.inventory.expiring-lots-email=${INVENTORY_EXPIRING_LOTS_EMAIL}