spring.flyway.locations=classpath:db/migration/hom
spring.flyway.enabled=false

aws.sqs.email-queue-url=${AWS_SQS_EMAIL_QUEUE_URL}

notifications.purchasing.approver-email=${PURCHASING_APPROVER_EMAIL}
notifications.inventory.expiring-lots-email=${INVENTORY_EXPIRING_LOTS_EMAIL}
notifications.crm.follow-up-email=${CRM_FOLLOW_UP_EMAIL}