spring.application.name=gravita

spring.datasource.url=jdbc:postgresql://localhost:5432/gravita
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

aws.region=us-east-1
