package br.gravita.core.ports.inbound.purchasing;

import br.gravita.core.domain.purchasing.PurchaseReturnId;

/**
 * UC-M6-09: creates a partial or total {@code PurchaseReturn} against a
 * confirmed {@code PurchaseReceipt}, reversing the stock entry and payable
 * generated by UC-M6-08 for the returned quantity and issuing a return NF-e
 * through M2's {@code IssueNfeUseCase} in the same flow.
 */
public interface ReturnToSupplierUseCase {
	PurchaseReturnId execute(ReturnToSupplierCommand command);
}
